### ISSUE TITLE
View image has many empty space

### ISSUE THREAD

**Issue by MiraiJR** [DATN-20/AI4Artists#114]
Current: 
- Nhìn cái form view của mk nó hiện tại rất dài và dư khoảng trống, không cân đối

Expected:
- Muốn nó nhìn cân đối và chủ yếu tập trung vào phần ảnh (đừng làm giống leonardo)
- Muốn cái ảnh hiển thị 
Ảnh
nội dung 
thay vì anh | nội dung như hiện tại

kiểu như trên theo t đề xuất 

Hoặc consider render tuỳ theo kích thước 

Attachment:
<img width="1120" alt="image" src="https://github.com/DATN-20/AI4Artists/assets/82590115/f95c288b-afd4-4b40-b6ae-415b5059b945">

**Comment by btdat1412** [comment]
Ảnh + nội dung sẽ quá dài 
Đã làm see more cho cái Prompt
